### ISSUE TITLE
Change parameters description in the golos control contract documentation.

### ISSUE THREAD

**Issue by e-schepachev** [cyberway/cyberway.documentation#113]
1)
"The structure containing setting parameters is as follows:"

This is not a structure. This is list of available parameters used by the contract. 

2)
multisig_acc — an account name...

Maybe something like: an account name controls a multisignature authorisation?

3)
It is not clear that the description of multisig_perms fields (like «two-thirds plus one») is default value and not a strong requirement.

**Comment by anazarov79** [comment]
1. "struct" has been replaced by "list"
2. The piece of text "an account name" has been replaced by "an account name that controls a multisignature authorisation"
3. "set by default" has been removed from the text.
