### ISSUE TITLE
The typo in 'the unregwitness action' section in th golos.control contract 

### ISSUE THREAD

**Issue by e-schepachev** [cyberway/cyberway.documentation#114]
In the description a regwitness instead of the unregwitness  is used:

The *regwitness* action can be called either by the candidate (in case of a withdrawal) or by a witness who found a discrepancy of the witness capabilities to desirable witness requirements, and mismatched data published on the web site with her/his relevant data.

**Comment by anazarov79** [comment]
The type has been corrected in golos.ctrl_contract file.
