### ISSUE TITLE
Call the unregwitness can only the candidate by himself.

### ISSUE THREAD

**Issue by e-schepachev** [cyberway/cyberway.documentation#115]
The regwitness action can be called either by the candidate (in case of a withdrawal) or *by a witness who found a discrepancy of the witness capabilities to desirable witness requirements, and mismatched data published on the web site with her/his relevant data*.

**Comment by anazarov79** [comment]
There is a mistake in golos.ctrl_contract.md file. The piece of text "The `regwitness` action can be called ..." is replaced by "The `unregwitness` action can be called ..."
